//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_fruit
    {
        public int id { get; set; }
        public string country { get; set; }
        public string item_type { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<double> unit_cost { get; set; }
        public string fruit { get; set; }
    }
}
